// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package builders

import (
	"di-comparison/shared"
)

// Injectors from app.go:

func BuildWireApplication() (*shared.Application, error) {
	param := shared.NewParam()
	firstDep := NewFirstDep(param)
	secondDep := NewSecondDep(param)
	application := NewApplication(firstDep, secondDep)
	return application, nil
}

// app.go:

type (
	FirstDep  *shared.SomeDependency
	SecondDep *shared.SomeDependency
)

func NewFirstDep(param shared.Param) FirstDep {
	return shared.NewSomeDependency(param)
}

func NewSecondDep(param shared.Param) SecondDep {
	return shared.NewSomeDependency(param)
}

func NewApplication(first FirstDep, second SecondDep) *shared.Application {
	return shared.NewApplication(first, second)
}
